apiVersion: certmanager.k8s.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <your email> # CHANGE_YOUR_EMAIL_HERE
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
